### ISSUE TITLE
False positive, failing to check for versions/technologies

### ISSUE THREAD

**Issue by WillSullivan** [OSSIndex/website#2]
My reference to NLog version 4.0.1 is throwing an error for a vulnerability listed in 1998 (!!!!!!) in its CGI scripts (!!!!?!?!?!!?!?!?!?!!?!?).

That's ... not really useful.  I don't see any information about versions/technologies, just a product name.  Is that the case?  Is there no way to weed out false positives like this?

**Comment by OSSIndex** [comment]
Thank you for your report. It appears we have a bug in the back-end code. I will resolve this and push a fix tonight.

As for false positive filtering, we currently do not have this in the tools but will add the feature to our roadmap. Which client tool are you using (Audit.NET, DevAudit, Audit.js, etc.)

**Comment by WillSullivan** [comment]
Audit.NET.  Thanks.

**Comment by OSSIndex** [comment]
It turns out there were 2 problems.

1. There was a server side issue that we have resolved for your particular case. It is possible the data has been cached on the client side so it may take a bit to clear. Otherwise you should be able to clear the cache (more detailed instructions below)
2. There is a client bug that could cause the same effect in other situations. This has been fixed and a new version of the client will be made available later on tonight or tomorrow.

I will be closing the issue once the fixed client is available, though you should see NLog working for you with the current client.

I have created a feature request for the filter, which I think would be very valuable. You can see it here: https://github.com/OSSIndex/audit.net/issues/2

Feedback on the proposed solution would be very welcome -- would it do what you would expect?

Thank you again for your feedback. These tools are new and in active development. Also note that the data in the back-end is rapidly evolving, we are identifying and adding new vulnerabilities (and vulnerability sources) daily. Any and all feedback and requests are appreciated.

Clearing the cache/Changing the cache timeout
-----------------------------------

1. Click the "Tools->Options..." menu item to get the options dialog
2. Look for "Audit.NET" in the left hand panel and select it
3. Change the value of the "Cache timeout". Set to -1 to disable the cache.

It is preferred that when possible the cache remain enabled since that will result in less traffic to the server, which you can understand is/will be an issue as we gain users.

**Comment by OSSIndex** [comment]
Note the server side fix/clearing the cache does not work, the client tool fix tonight/tomorrow will definitely fix the issue for you.

**Comment by OSSIndex** [comment]
A new release has been created at [GitHub](https://github.com/OSSIndex/audit.net/releases/tag/1.2.7) and uploaded to the [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/73493090-b219-452a-989e-e3d228023927)
