### ISSUE TITLE
Email address does not work

### ISSUE THREAD

**Issue by rtfpessoa** [OSSIndex/website#24]
The email found in https://ossindex.net/public/restapi2 does not seem to work, gmail returned my email.

How can I contact someone about the api?

**Comment by ken-duck** [comment]
Thank you for mentioning this. I will work on making sure this email address is created. Meanwhile the best address to use would be info@vorsecurity.com (which is the old address). Mail there will still come to me (as will mail for the new address once it is working).

**Comment by ken-duck** [comment]
Ahh! It is also a typo. The correct address should be ossindex@sonatype.**org**

I will fix the website, but it might take a bit cause I am away from the office at the moment (meetings) and it will take me a bit to get my environment set up to do the update. I will endeavour to fix it soon.

Meanwhile, you should find one of ossindex@sonatype.org or info@vorsecurity.com should work.

**Comment by rtfpessoa** [comment]
Done. Thanks for the quick response. 👍

**Comment by ken-duck** [comment]
Hmm. I know at least one of those addresses *should* work because I normally get mail from them, but I tried some testing and am not seeing them at the moment. It could be that they are just delayed (cause they are redirects), or something is wrong. If you send the email one more time to kduck@sonatype.com I *know* I will receive it. Once I hear from you I will delete this comment so I can hopefully avoid the spam bots finding it :)

**Comment by rtfpessoa** [comment]
@ken-duck done

**Comment by rtfpessoa** [comment]
@ken-duck let me know if you got it.

**Comment by ken-duck** [comment]
Yup. I am responding now...
